name: Build
on:
  push:
    branches:
    - '*' 
    tags:
    - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          npm install
          npm run test
          npm run build
